
import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Random;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author faysa
 */
public class Ticketing extends javax.swing.JFrame {
    

    /**
     * Creates new form Ticketing
     */
    public Ticketing() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        shuvon = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jradult = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jrsingle = new javax.swing.JRadioButton();
        jRadioButton7 = new javax.swing.JRadioButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<String>();
        jLabel23 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jlblclass = new javax.swing.JTextField();
        jlbltype = new javax.swing.JTextField();
        jlblno = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jlblfrom = new javax.swing.JTextField();
        jlblto = new javax.swing.JTextField();
        jlbldate = new javax.swing.JTextField();
        jlbltime = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jlblprice = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jlblSub = new javax.swing.JTextField();
        jlblVAT = new javax.swing.JTextField();
        jlblTotal = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(224, 28, 145));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 60)); // NOI18N
        jLabel1.setText("Train Ticketing System");
        jLabel1.setToolTipText("");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(181, 3, 892, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1470, 80));

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Firstname");
        jLabel2.setToolTipText("");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 140, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("Lastname");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setText("Address");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setText("Phone No");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setText("Post Code");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel2.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 200, 30));

        jTextField2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel2.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 200, 30));

        jTextField3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jPanel2.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 200, 30));

        jTextField4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel2.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 200, 30));

        jTextField5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel2.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 200, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 370, 280));

        jPanel3.setBackground(new java.awt.Color(255, 102, 102));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jRadioButton1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jRadioButton1.setText("AC");
        jPanel3.add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 53, -1, -1));

        jRadioButton2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jRadioButton2.setText("First Class");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        shuvon.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        shuvon.setText("Shovan");
        jPanel3.add(shuvon, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setText("Class");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 17, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setText("Ticket Select");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 17, -1, -1));

        jradult.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jradult.setText("Adult");
        jPanel3.add(jradult, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 59, -1, -1));

        jRadioButton5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jRadioButton5.setText("Child");
        jPanel3.add(jRadioButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, -1, -1));

        jrsingle.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jrsingle.setText("Single");
        jPanel3.add(jrsingle, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, -1, -1));

        jRadioButton7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jRadioButton7.setText("Return");
        jPanel3.add(jRadioButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, -1, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 370, 230));

        jPanel4.setBackground(new java.awt.Color(153, 153, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel9.setText("Source");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 14, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel10.setText("Destination ");
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 14, -1, -1));

        jComboBox3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Mymensingh", "Chittagong", "Jessore", "Sylhet", "Barisal", " ", " " }));
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });
        jPanel4.add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 78, -1, -1));

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel23.setText("Dhaka");
        jPanel4.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 100, 40));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 590, 370, 150));

        jPanel5.setBackground(new java.awt.Color(255, 153, 153));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel11.setText("Class");
        jPanel5.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 29, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel12.setText("Type");
        jPanel5.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 24, 90, 39));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel13.setText("Ticket no");
        jPanel5.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(451, 29, -1, -1));

        jlblclass.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jlblclass.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel5.add(jlblclass, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 70, 147, 34));

        jlbltype.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jlbltype.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel5.add(jlbltype, new org.netbeans.lib.awtextra.AbsoluteConstraints(237, 69, 145, 36));

        jlblno.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jlblno.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel5.add(jlblno, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 70, 161, 37));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel14.setText("From");
        jPanel5.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 137, -1, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel15.setText("To");
        jPanel5.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 212, -1, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel16.setText("Date");
        jPanel5.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 299, -1, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel17.setText("Time");
        jPanel5.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 358, -1, -1));

        jlblfrom.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jlblfrom.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jlblfrom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jlblfromActionPerformed(evt);
            }
        });
        jPanel5.add(jlblfrom, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 133, 193, -1));

        jlblto.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jlblto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jlblto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jlbltoActionPerformed(evt);
            }
        });
        jPanel5.add(jlblto, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 209, 193, 32));

        jlbldate.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jlbldate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel5.add(jlbldate, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 294, 193, 34));

        jlbltime.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jlbltime.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel5.add(jlbltime, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 356, 193, 31));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel18.setText("Price");
        jPanel5.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 210, 68, -1));

        jlblprice.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jlblprice.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel5.add(jlblprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 250, 168, 47));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 80, 600, 430));

        jPanel6.setBackground(new java.awt.Color(167, 101, 217));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel19.setText("Sub Total");
        jPanel6.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 26, -1, -1));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel20.setText("VAT");
        jPanel6.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 77, -1, -1));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel21.setText("Total");
        jPanel6.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 138, -1, -1));

        jlblSub.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jlblSub.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel6.add(jlblSub, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 24, 192, -1));

        jlblVAT.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jlblVAT.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jlblVAT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jlblVATActionPerformed(evt);
            }
        });
        jPanel6.add(jlblVAT, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 77, 192, -1));

        jlblTotal.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jlblTotal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel6.add(jlblTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 136, 192, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton1.setText("Total");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(458, 24, -1, -1));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton2.setText("Reset");
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 80, -1, -1));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton3.setText("Exit");
        jButton3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 130, -1, -1));

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 510, 600, 230));

        jPanel7.setBackground(new java.awt.Color(240, 111, 54));
        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel22.setBackground(java.awt.Color.red);
        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel22.setText("Receipt");
        jPanel7.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 33, 155, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setBorder(new javax.swing.border.MatteBorder(null));
        jScrollPane1.setViewportView(jTextArea1);

        jPanel7.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 430, 444));

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton4.setText("Receipt");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 550, 140, 40));

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton5.setText("Exit");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 550, 110, 40));

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 80, 500, 660));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed
private JFrame frame;
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
       frame=new JFrame("Exit");
       if(JOptionPane.showConfirmDialog( frame,"confirm if you want to exit","Ticketing System",JOptionPane.YES_NO_OPTION)== JOptionPane.YES_NO_OPTION){
           System.exit(0);
       }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       frame=new JFrame("Exit");
       if(JOptionPane.showConfirmDialog( frame,"confirm if you want to exit","Ticketing System",JOptionPane.YES_NO_OPTION)== JOptionPane.YES_NO_OPTION){
           System.exit(0);
       }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
jlblVAT.setText(null);
jlblSub.setText(null);
jlblTotal.setText(null);
jlbltime.setText(null);
jlbldate.setText(null);
jlblto.setText(null);
jlblprice.setText(null);
jlblfrom.setText(null);
jlblclass.setText(null);
jlbltype.setText(null);
jlblno.setText(null);
jTextField1.setText("");
jTextField2.setText("");
jTextField3.setText("");
jTextField4.setText("");
jTextField5.setText("");
jRadioButton1.setSelected(false);
jRadioButton2.setSelected(false);
shuvon.setSelected(false);
jradult.setSelected(false);
jrsingle.setSelected(false);
jRadioButton5.setSelected(false);
jRadioButton7.setSelected(false);
jComboBox3.setSelectedItem("none");
jTextArea1.setText("");





 
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jlblVATActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jlblVATActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jlblVATActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        this.getContentPane().setBackground(Color.BLACK);
    }//GEN-LAST:event_formWindowActivated

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       Calendar timer=Calendar.getInstance();
       timer.getTime();
       SimpleDateFormat tTime=new SimpleDateFormat("HH:mm:ss");
       jlbltime.setText(tTime.format(timer.getTime()));
       
        SimpleDateFormat tdate=new SimpleDateFormat("dd-MMM-YYYY");
        jlbldate.setText(tdate.format(timer.getTime()));
        
        jlblfrom.setText("Dhaka ");
    jlblto.setText((String) jComboBox3.getSelectedItem());
    
        int num1;
        String q1="";
        num1=100 +(int) (Math.random()*1000);
        q1 +=num1+ 100;
        jlblno.setText(q1);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
double VAT=19.50;
double MilesK8=125.78;
double MilesK12=135.10;
double MilesK20=162.23;
double MilesK25=229.78;
double Miles30=255.78;
double totalCost, fclass=111.85,ac=511.60;
if ((shuvon.isSelected())&&  (jrsingle.isSelected()) && (jradult.isSelected()&&(jComboBox3.getSelectedItem().equals("Mymensingh"))
        ))
{
 totalCost=(VAT * MilesK8)/100;
String vat=String.format("৳%.2f", totalCost);
 jlblVAT.setText(vat);
 
 String sub=String.format("৳%.2f", MilesK8);
 jlblSub.setText(sub);
 
 String total=String.format("৳%.2f", MilesK8+totalCost);
 jlblTotal.setText(total);
 jlblprice.setText(total);
 jlbltype.setText("Adult");
 jlblclass.setText("Shuvon");
 
}

else if ((shuvon.isSelected())&&  (jRadioButton7.isSelected()) && (jradult.isSelected()&&(jComboBox3.getSelectedItem().equals("Mymensingh"))
        ))
{
 totalCost=(VAT * MilesK8 *2)/100;
String vat=String.format("৳%.2f", totalCost*2);
 jlblVAT.setText(vat);
 
 String sub=String.format("৳%.2f", MilesK8*2);
 jlblSub.setText(sub);
 
 String total=String.format("৳%.2f", MilesK8+totalCost*2);
 jlblTotal.setText(total);
 jlblprice.setText(total);
 jlbltype.setText("Adult");
 jlblclass.setText("Shuvon");
 
}

else if ((shuvon.isSelected())&&  (jrsingle.isSelected()) && (jRadioButton5.isSelected()&&(jComboBox3.getSelectedItem().equals("Mymensingh"))
        ))
{
 totalCost=(VAT * MilesK8 -18)/100;
String vat=String.format("৳%.2f", totalCost -18);
 jlblVAT.setText(vat);
 
 String sub=String.format("৳%.2f", MilesK8 -18);
 jlblSub.setText(sub);
 
 String total=String.format("৳%.2f", MilesK8+totalCost -18);
 jlblTotal.setText(total);
 jlblprice.setText(total);
 jlbltype.setText("Child");
 jlblclass.setText("Shuvon");
 
}
else if ((shuvon.isSelected())&&  (jRadioButton7.isSelected()) && (jRadioButton5.isSelected()&&(jComboBox3.getSelectedItem().equals("Mymensingh"))
        ))
{
 totalCost=(VAT * MilesK8 -18)/100;
String vat=String.format("৳%.2f", totalCost -18);
 jlblVAT.setText(vat);
 
 String sub=String.format("৳%.2f", MilesK8 *2);
 jlblSub.setText(sub);
 
 String total=String.format("৳%.2f", (MilesK8+totalCost*2) -18);
 jlblTotal.setText(total);
 jlblprice.setText(total);
 jlbltype.setText("Child");
 jlblclass.setText("Shuvon");
 
}


else if ((shuvon.isSelected())&&  (jrsingle.isSelected()) && (jradult.isSelected()&&(jComboBox3.getSelectedItem().equals("Chittagong"))
        ))
{
 totalCost=(VAT * MilesK12)/100;
String vat=String.format("৳%.2f", totalCost);
 jlblVAT.setText(vat);
 
 String sub=String.format("৳%.2f", MilesK12);
 jlblSub.setText(sub);
 
 String total=String.format("৳%.2f", MilesK12+totalCost);
 jlblTotal.setText(total);
 jlblprice.setText(total);
 jlbltype.setText("Adult");
 jlblclass.setText("Shuvon");
 
}

else if ((shuvon.isSelected())&&  (jRadioButton7.isSelected()) && (jradult.isSelected()&&(jComboBox3.getSelectedItem().equals("Chittagong"))
        ))
{
 totalCost=(VAT * MilesK8 *2)/100;
String vat=String.format("৳%.2f", totalCost*2);
 jlblVAT.setText(vat);
 
 String sub=String.format("৳%.2f", MilesK12*2);
 jlblSub.setText(sub);
 
 String total=String.format("৳%.2f", MilesK12+totalCost*2);
 jlblTotal.setText(total);
 jlblprice.setText(total);
 jlbltype.setText("Adult");
 jlblclass.setText("Shuvon");
 
}

else if ((shuvon.isSelected())&&  (jrsingle.isSelected()) && (jRadioButton5.isSelected()&&(jComboBox3.getSelectedItem().equals("Chittagong"))
        ))
{
 totalCost=(VAT * MilesK12 -18)/100;
String vat=String.format("৳%.2f", totalCost -18);
 jlblVAT.setText(vat);
 
 String sub=String.format("৳%.2f", MilesK12 -18);
 jlblSub.setText(sub);
 
 String total=String.format("৳%.2f", MilesK12+totalCost -18);
 jlblTotal.setText(total);
 jlblprice.setText(total);
 jlbltype.setText("Child");
 jlblclass.setText("Shuvon");
 
}
else if ((shuvon.isSelected())&&  (jRadioButton7.isSelected()) && (jRadioButton5.isSelected()&&(jComboBox3.getSelectedItem().equals("Chittagong"))
        ))
{
 totalCost=(VAT * MilesK12 -18)/100;
String vat=String.format("৳%.2f", totalCost -18);
 jlblVAT.setText(vat);
 
 String sub=String.format("৳%.2f", MilesK12);
 jlblSub.setText(sub);
 
 String total=String.format("৳%.2f", (MilesK12+totalCost*2) -18);
 jlblTotal.setText(total);
 jlblprice.setText(total);
 jlbltype.setText("Child");
 jlblclass.setText("Shuvon");
 
}


else if ((shuvon.isSelected())&&  (jrsingle.isSelected()) && (jradult.isSelected()&&(jComboBox3.getSelectedItem().equals("Jessore"))
        ))
{
 totalCost=(VAT * MilesK20)/100;
String vat=String.format("৳%.2f", totalCost);
 jlblVAT.setText(vat);
 
 String sub=String.format("৳%.2f", MilesK20);
 jlblSub.setText(sub);
 
 String total=String.format("৳%.2f", MilesK20+totalCost);
 jlblTotal.setText(total);
 jlblprice.setText(total);
 jlbltype.setText("Adult");
 jlblclass.setText("Shuvon");
 
}

else if ((shuvon.isSelected())&&  (jRadioButton7.isSelected()) && (jradult.isSelected()&&(jComboBox3.getSelectedItem().equals("Jessore"))
        ))
{
 totalCost=(VAT * MilesK20 *2)/100;
String vat=String.format("৳%.2f", totalCost*2);
 jlblVAT.setText(vat);
 
 String sub=String.format("৳%.2f", MilesK20*2);
 jlblSub.setText(sub);
 
 String total=String.format("৳%.2f", MilesK20+totalCost*2);
 jlblTotal.setText(total);
 jlblprice.setText(total);
 jlbltype.setText("Adult");
 jlblclass.setText("Shuvon");
}

else if ((shuvon.isSelected())&&  (jrsingle.isSelected()) && (jRadioButton5.isSelected()&&(jComboBox3.getSelectedItem().equals("Jessore"))
        ))
{
 totalCost=(VAT * MilesK20 -18)/100;
String vat=String.format("৳%.2f", totalCost -18);
 jlblVAT.setText(vat);
 
 String sub=String.format("৳%.2f", MilesK20 -18);
 jlblSub.setText(sub);
 
 String total=String.format("৳%.2f", MilesK20+totalCost -18);
 jlblTotal.setText(total);
 jlblprice.setText(total);
 jlbltype.setText("Child");
 jlblclass.setText("Shuvon");
 
}
else if ((shuvon.isSelected())&&  (jRadioButton7.isSelected()) && (jRadioButton5.isSelected()&&(jComboBox3.getSelectedItem().equals("Jessore"))
        ))
{
 totalCost=(VAT * MilesK20 -18)/100;
String vat=String.format("৳%.2f", totalCost -18);
 jlblVAT.setText(vat);
 
 String sub=String.format("৳%.2f", MilesK20*2);
 jlblSub.setText(sub);
 
 String total=String.format("৳%.2f", (MilesK20+totalCost*2) -18);
 jlblTotal.setText(total);
 jlblprice.setText(total);
 jlbltype.setText("Child");
 jlblclass.setText("Shuvon");
 
}



else if ((shuvon.isSelected())&&  (jrsingle.isSelected()) && (jradult.isSelected()&&(jComboBox3.getSelectedItem().equals("Sylhet"))
        ))
{
 totalCost=(VAT * MilesK25)/100;
String vat=String.format("৳%.2f", totalCost);
 jlblVAT.setText(vat);
 
 String sub=String.format("৳%.2f", MilesK25);
 jlblSub.setText(sub);
 
 String total=String.format("৳%.2f", MilesK25+totalCost);
 jlblTotal.setText(total);
 jlblprice.setText(total);
 jlbltype.setText("Adult");
 jlblclass.setText("Shuvon");
 
}

else if ((shuvon.isSelected())&&  (jRadioButton7.isSelected()) && (jradult.isSelected()&&(jComboBox3.getSelectedItem().equals("Sylhet"))
        ))
{
 totalCost=(VAT * MilesK25 *2)/100;
String vat=String.format("৳%.2f", totalCost*2);
 jlblVAT.setText(vat);
 
 String sub=String.format("৳%.2f", MilesK25*2);
 jlblSub.setText(sub);
 
 String total=String.format("৳%.2f", MilesK25+totalCost*2);
 jlblTotal.setText(total);
 jlblprice.setText(total);
 jlbltype.setText("Adult");
 jlblclass.setText("Shuvon");
 
}

else if ((shuvon.isSelected())&&  (jrsingle.isSelected()) && (jRadioButton5.isSelected()&&(jComboBox3.getSelectedItem().equals("Sylhet"))
        ))
{
 totalCost=(VAT * MilesK25 -18)/100;
String vat=String.format("৳%.2f", totalCost -18);
 jlblVAT.setText(vat);
 
 String sub=String.format("৳%.2f", MilesK25 -18);
 jlblSub.setText(sub);
 
 String total=String.format("৳%.2f", MilesK25+totalCost -18);
 jlblTotal.setText(total);
 jlblprice.setText(total);
 jlbltype.setText("Child");
 jlblclass.setText("Shuvon");
 
}
else if ((shuvon.isSelected())&&  (jRadioButton7.isSelected()) && (jRadioButton5.isSelected()&&(jComboBox3.getSelectedItem().equals("Sylhet"))
        ))
{
 totalCost=(VAT * MilesK25 -18)/100;
String vat=String.format("৳%.2f", totalCost -18);
 jlblVAT.setText(vat);
 
 String sub=String.format("৳%.2f", MilesK25*2);
 jlblSub.setText(sub);
 
 String total=String.format("৳%.2f", (MilesK25+totalCost*2) -18);
 jlblTotal.setText(total);
 jlblprice.setText(total);
 jlbltype.setText("Child");
 jlblclass.setText("Shuvon");
}



else if ((shuvon.isSelected())&&  (jrsingle.isSelected()) && (jradult.isSelected()&&(jComboBox3.getSelectedItem().equals("Barisal"))
        ))
{
 totalCost=(VAT * MilesK25)/100;
String vat=String.format("৳%.2f", totalCost);
 jlblVAT.setText(vat);
 
 String sub=String.format("৳%.2f", Miles30);
 jlblSub.setText(sub);
 
 String total=String.format("৳%.2f", Miles30+totalCost);
 jlblTotal.setText(total);
 jlblprice.setText(total);
 jlbltype.setText("Adult");
 jlblclass.setText("Shuvon");
 
}

else if ((shuvon.isSelected())&&  (jRadioButton7.isSelected()) && (jradult.isSelected()&&(jComboBox3.getSelectedItem().equals("Barisal"))
        ))
{
 totalCost=(VAT * Miles30 *2)/100;
String vat=String.format("৳%.2f", totalCost*2);
 jlblVAT.setText(vat);
 
 String sub=String.format("৳%.2f", Miles30*2);
 jlblSub.setText(sub);
 
 String total=String.format("৳%.2f", Miles30+totalCost*2);
 jlblTotal.setText(total);
 jlblprice.setText(total);
 jlbltype.setText("Adult");
 jlblclass.setText("Shuvon");
 
}

else if ((shuvon.isSelected())&&  (jrsingle.isSelected()) && (jRadioButton5.isSelected()&&(jComboBox3.getSelectedItem().equals("Barisal"))
        ))
{
 totalCost=(VAT * Miles30 -18)/100;
String vat=String.format("৳%.2f", totalCost -18);
 jlblVAT.setText(vat);
 
 String sub=String.format("৳%.2f", Miles30 -18);
 jlblSub.setText(sub);
 
 String total=String.format("৳%.2f", Miles30+totalCost -18);
 jlblTotal.setText(total);
 jlblprice.setText(total);
 jlbltype.setText("Child");
 jlblclass.setText("Shuvon");
 
}
else if ((shuvon.isSelected())&&  (jRadioButton7.isSelected()) && (jRadioButton5.isSelected()&&(jComboBox3.getSelectedItem().equals("Barisal"))
        ))
{
 totalCost=(VAT * Miles30 -18)/100;
String vat=String.format("৳%.2f", totalCost -18);
 jlblVAT.setText(vat);
 
 String sub=String.format("৳%.2f", Miles30*2);
 jlblSub.setText(sub);
 
 String total=String.format("৳%.2f", (Miles30+totalCost*2) -18);
 jlblTotal.setText(total);
 jlblprice.setText(total);
 jlbltype.setText("Child");
 jlblclass.setText("Shuvon");
 
}
else if ((jRadioButton2.isSelected())&&  (jrsingle.isSelected()) && (jradult.isSelected()&&(jComboBox3.getSelectedItem().equals("Mymensingh"))
        ))
{
 totalCost=(VAT * (MilesK8+fclass))/100;
String vat=String.format("৳%.2f", totalCost);
 jlblVAT.setText(vat);
 
 String sub=String.format("৳%.2f", MilesK8+fclass);
 jlblSub.setText(sub);
 
 String total=String.format("৳%.2f", MilesK8+totalCost+fclass);
 jlblTotal.setText(total);
 jlblprice.setText(total);
 jlbltype.setText("Adult");
 jlblclass.setText("First Class");
 
}

else if ((jRadioButton2.isSelected())&&  (jRadioButton7.isSelected()) && (jradult.isSelected()&&(jComboBox3.getSelectedItem().equals("Mymensingh"))
        ))
{
 totalCost=(VAT * MilesK8+fclass *2)/100;
String vat=String.format("৳%.2f", (totalCost)*2);
 jlblVAT.setText(vat);
 
 String sub=String.format("৳%.2f", MilesK8+fclass*2);
 jlblSub.setText(sub);
 
 String total=String.format("৳%.2f", MilesK8+fclass+totalCost*2);
 jlblTotal.setText(total);
 jlblprice.setText(total);
 jlbltype.setText("Adult");
 jlblclass.setText("First Class");
 
}

else if ((jRadioButton2.isSelected())&&  (jrsingle.isSelected()) && (jRadioButton5.isSelected()&&(jComboBox3.getSelectedItem().equals("Mymensingh"))
        ))
{
 totalCost=(VAT * MilesK8+fclass-18)/100;
String vat=String.format("৳%.2f", totalCost -18);
 jlblVAT.setText(vat);
 
 String sub=String.format("৳%.2f", MilesK8+fclass -18);
 jlblSub.setText(sub);
 
 String total=String.format("৳%.2f", MilesK8+totalCost+fclass -18);
 jlblTotal.setText(total);
 jlblprice.setText(total);
 jlbltype.setText("Child");
 jlblclass.setText("First Class");
 
}
else if ((jRadioButton2.isSelected())&&  (jRadioButton7.isSelected()) && (jRadioButton5.isSelected()&&(jComboBox3.getSelectedItem().equals("Mymensingh"))
        ))
{
 totalCost=(VAT * MilesK8+fclass -18)/100;
String vat=String.format("৳%.2f", totalCost -18);
 jlblVAT.setText(vat);
 
 String sub=String.format("৳%.2f", MilesK8+fclass *2);
 jlblSub.setText(sub);
 
 String total=String.format("৳%.2f", (MilesK8+fclass+totalCost*2) -18);
 jlblTotal.setText(total);
 jlblprice.setText(total);
 jlbltype.setText("Child");
 jlblclass.setText("First Class");
 
}


else if ((jRadioButton2.isSelected())&&  (jrsingle.isSelected()) && (jradult.isSelected()&&(jComboBox3.getSelectedItem().equals("Chittagong"))
        ))
{
 totalCost=(VAT * MilesK12+fclass)/100;
String vat=String.format("৳%.2f", totalCost);
 jlblVAT.setText(vat);
 
 String sub=String.format("৳%.2f", MilesK12+fclass);
 jlblSub.setText(sub);
 
 String total=String.format("৳%.2f", MilesK12+fclass+totalCost);
 jlblTotal.setText(total);
 jlblprice.setText(total);
 jlbltype.setText("Adult");
 jlblclass.setText("First Class");
 
}

else if ((jRadioButton2.isSelected())&&  (jRadioButton7.isSelected()) && (jradult.isSelected()&&(jComboBox3.getSelectedItem().equals("Chittagong"))
        ))
{
 totalCost=(VAT * MilesK8+fclass *2)/100;
String vat=String.format("৳%.2f", totalCost*2);
 jlblVAT.setText(vat);
 
 String sub=String.format("৳%.2f", MilesK12+fclass*2);
 jlblSub.setText(sub);
 
 String total=String.format("৳%.2f", MilesK12+fclass+totalCost*2);
 jlblTotal.setText(total);
 jlblprice.setText(total);
 jlbltype.setText("Adult");
 jlblclass.setText("First Class");
 
}

else if ((jRadioButton2.isSelected())&&  (jrsingle.isSelected()) && (jRadioButton5.isSelected()&&(jComboBox3.getSelectedItem().equals("Chittagong"))
        ))
{
 totalCost=(VAT * MilesK12+fclass-18)/100;
String vat=String.format("৳%.2f", totalCost -18);
 jlblVAT.setText(vat);
 
 String sub=String.format("৳%.2f", MilesK12+fclass -18);
 jlblSub.setText(sub);
 
 String total=String.format("৳%.2f", MilesK12+fclass+totalCost -18);
 jlblTotal.setText(total);
 jlblprice.setText(total);
 jlbltype.setText("Child");
 jlblclass.setText("First Class");
 
}
else if ((jRadioButton2.isSelected())&&  (jRadioButton7.isSelected()) && (jRadioButton5.isSelected()&&(jComboBox3.getSelectedItem().equals("Chittagong"))
        ))
{
 totalCost=(VAT * MilesK12+fclass -18)/100;
String vat=String.format("৳%.2f", totalCost -18);
 jlblVAT.setText(vat);
 
 String sub=String.format("৳%.2f", MilesK12+fclass);
 jlblSub.setText(sub);
 
 String total=String.format("৳%.2f", (MilesK12+fclass+totalCost*2) -18);
 jlblTotal.setText(total);
 jlblprice.setText(total);
 jlbltype.setText("Child");
 jlblclass.setText("First Class");
 
}


else if ((jRadioButton2.isSelected())&&  (jrsingle.isSelected()) && (jradult.isSelected()&&(jComboBox3.getSelectedItem().equals("Jessore"))
        ))
{
 totalCost=(VAT * MilesK20+fclass)/100;
String vat=String.format("৳%.2f", totalCost);
 jlblVAT.setText(vat);
 
 String sub=String.format("৳%.2f", MilesK20+fclass);
 jlblSub.setText(sub);
 
 String total=String.format("৳%.2f", MilesK20+fclass+totalCost);
 jlblTotal.setText(total);
 jlblprice.setText(total);
 jlbltype.setText("Adult");
 jlblclass.setText("First Class");
 
}

else if ((jRadioButton2.isSelected())&&  (jRadioButton7.isSelected()) && (jradult.isSelected()&&(jComboBox3.getSelectedItem().equals("Jessore"))
        ))
{
 totalCost=(VAT * MilesK20+fclass *2)/100;
String vat=String.format("৳%.2f", totalCost*2);
 jlblVAT.setText(vat);
 
 String sub=String.format("৳%.2f", MilesK20+fclass*2);
 jlblSub.setText(sub);
 
 String total=String.format("৳%.2f", MilesK20+fclass+totalCost*2);
 jlblTotal.setText(total);
 jlblprice.setText(total);
 jlbltype.setText("Adult");
 jlblclass.setText("First Class");
 
}

else if ((jRadioButton2.isSelected())&&  (jrsingle.isSelected()) && (jRadioButton5.isSelected()&&(jComboBox3.getSelectedItem().equals("Jessore"))
        ))
{
 totalCost=(VAT * MilesK20+fclass -18)/100;
String vat=String.format("৳%.2f", totalCost -18);
 jlblVAT.setText(vat);
 
 String sub=String.format("৳%.2f", MilesK20+fclass -18);
 jlblSub.setText(sub);
 
 String total=String.format("৳%.2f", MilesK20+fclass+totalCost -18);
 jlblTotal.setText(total);
 jlblprice.setText(total);
 jlbltype.setText("Child");
 jlblclass.setText("First Class");
}
else if ((jRadioButton2.isSelected())&&  (jRadioButton7.isSelected()) && (jRadioButton5.isSelected()&&(jComboBox3.getSelectedItem().equals("Jessore"))
        ))
{
 totalCost=(VAT * MilesK20+fclass-18)/100;
String vat=String.format("৳%.2f", totalCost -18);
 jlblVAT.setText(vat);
 
 String sub=String.format("৳%.2f", MilesK20+fclass*2);
 jlblSub.setText(sub);
 
 String total=String.format("৳%.2f", (MilesK20+fclass+totalCost*2) -18);
 jlblTotal.setText(total);
 jlblprice.setText(total);
 jlbltype.setText("Child");
 jlblclass.setText("First Class");
}



else if ((jRadioButton2.isSelected())&&  (jrsingle.isSelected()) && (jradult.isSelected()&&(jComboBox3.getSelectedItem().equals("Sylhet"))
        ))
{
 totalCost=(VAT * MilesK25+fclass)/100;
String vat=String.format("৳%.2f", totalCost);
 jlblVAT.setText(vat);
 
 String sub=String.format("৳%.2f", MilesK25+fclass);
 jlblSub.setText(sub);
 
 String total=String.format("৳%.2f", MilesK25+totalCost+fclass);
 jlblTotal.setText(total);
 jlblprice.setText(total);
 jlbltype.setText("Adult");
 jlblclass.setText("First Class");
}

else if ((jRadioButton2.isSelected())&&  (jRadioButton7.isSelected()) && (jradult.isSelected()&&(jComboBox3.getSelectedItem().equals("Sylhet"))
        ))
{
 totalCost=(VAT * MilesK25+fclass*2)/100;
String vat=String.format("৳%.2f", totalCost*2);
 jlblVAT.setText(vat);
 
 String sub=String.format("৳%.2f", MilesK25+fclass*2);
 jlblSub.setText(sub);
 
 String total=String.format("৳%.2f", MilesK25+fclass+totalCost*2);
 jlblTotal.setText(total);
 jlblprice.setText(total);
 jlbltype.setText("Adult");
 jlblclass.setText("First Class");
}

else if ((jRadioButton2.isSelected())&&  (jrsingle.isSelected()) && (jRadioButton5.isSelected()&&(jComboBox3.getSelectedItem().equals("Sylhet"))
        ))
{
 totalCost=(VAT * MilesK25+fclass-18)/100;
String vat=String.format("৳%.2f", totalCost-18);
 jlblVAT.setText(vat);
 
 String sub=String.format("৳%.2f", MilesK25+fclass -18);
 jlblSub.setText(sub);
 
 String total=String.format("৳%.2f", MilesK25+fclass+totalCost -18);
 jlblTotal.setText(total);
 jlblprice.setText(total);
 jlbltype.setText("Child");
 jlblclass.setText("First Class");
}
else if ((jRadioButton2.isSelected())&&  (jRadioButton7.isSelected()) && (jRadioButton5.isSelected()&&(jComboBox3.getSelectedItem().equals("Sylhet"))
        ))
{
 totalCost=(VAT * MilesK25+fclass -18)/100;
String vat=String.format("৳%.2f", totalCost -18);
 jlblVAT.setText(vat);
 
 String sub=String.format("৳%.2f", MilesK25+fclass*2);
 jlblSub.setText(sub);
 
 String total=String.format("৳%.2f", (MilesK25+fclass+totalCost*2) -18);
 jlblTotal.setText(total);
 jlblprice.setText(total);
 jlbltype.setText("Child");
 jlblclass.setText("First Class");
}



else if ((jRadioButton2.isSelected())&&  (jrsingle.isSelected()) && (jradult.isSelected()&&(jComboBox3.getSelectedItem().equals("Barisal"))
        ))
{
 totalCost=(VAT * MilesK25+fclass)/100;
String vat=String.format("৳%.2f", totalCost);
 jlblVAT.setText(vat);
 
 String sub=String.format("৳%.2f", Miles30+fclass);
 jlblSub.setText(sub);
 
 String total=String.format("৳%.2f", Miles30+totalCost+fclass);
 jlblTotal.setText(total);
 jlblprice.setText(total);
 jlbltype.setText("Adult");
 jlblclass.setText("First Class");
}

else if ((jRadioButton2.isSelected())&&  (jRadioButton7.isSelected()) && (jradult.isSelected()&&(jComboBox3.getSelectedItem().equals("Barisal"))
        ))
{
 totalCost=(VAT * Miles30+fclass *2)/100;
String vat=String.format("৳%.2f", totalCost*2);
 jlblVAT.setText(vat);
 
 String sub=String.format("৳%.2f", Miles30+fclass*2);
 jlblSub.setText(sub);
 
 String total=String.format("৳%.2f", Miles30+fclass+totalCost*2);
 jlblTotal.setText(total);
 jlblprice.setText(total);
 jlbltype.setText("Adult");
 jlblclass.setText("First Class");
}

else if ((jRadioButton2.isSelected())&&  (jrsingle.isSelected()) && (jRadioButton5.isSelected()&&(jComboBox3.getSelectedItem().equals("Barisal"))
        ))
{
 totalCost=(VAT * Miles30+fclass -18)/100;
String vat=String.format("৳%.2f", totalCost -18);
 jlblVAT.setText(vat);
 
 String sub=String.format("৳%.2f", Miles30+fclass -18);
 jlblSub.setText(sub);
 
 String total=String.format("৳%.2f", Miles30+totalCost+fclass -18);
 jlblTotal.setText(total);
 jlblprice.setText(total);
 jlbltype.setText("Child");
 jlblclass.setText("First Class");
}
else if ((jRadioButton2.isSelected())&&  (jRadioButton7.isSelected()) && (jRadioButton5.isSelected()&&(jComboBox3.getSelectedItem().equals("Barisal"))
        ))
{
 totalCost=(VAT * Miles30+fclass-18)/100;
String vat=String.format("৳%.2f", totalCost -18);
 jlblVAT.setText(vat);
 
 String sub=String.format("৳%.2f", Miles30+fclass*2);
 jlblSub.setText(sub);
 
 String total=String.format("৳%.2f", (Miles30+totalCost+fclass*2) -18);
 jlblTotal.setText(total);
 jlblprice.setText(total);
 jlbltype.setText("Child");
 jlblclass.setText("First Class");
}




else if ((jRadioButton1.isSelected())&&  (jrsingle.isSelected()) && (jradult.isSelected()&&(jComboBox3.getSelectedItem().equals("Mymensingh"))
        ))
{
 totalCost=(VAT * MilesK8+ac)/100;
String vat=String.format("৳%.2f", totalCost);
 jlblVAT.setText(vat);
 
 String sub=String.format("৳%.2f", MilesK8+ac);
 jlblSub.setText(sub);
 
 String total=String.format("৳%.2f", MilesK8+totalCost+ac);
 jlblTotal.setText(total);
 jlblprice.setText(total);
 jlbltype.setText("Adult");
 jlblclass.setText("AC");
}

else if ((jRadioButton1.isSelected())&&  (jRadioButton7.isSelected()) && (jradult.isSelected()&&(jComboBox3.getSelectedItem().equals("Mymensingh"))
        ))
{
 totalCost=(VAT * MilesK8+ac *2)/100;
String vat=String.format("৳%.2f", totalCost*2);
 jlblVAT.setText(vat);
 
 String sub=String.format("৳%.2f", MilesK8+ac*2);
 jlblSub.setText(sub);
 
 String total=String.format("৳%.2f", MilesK8+ac+totalCost*2);
 jlblTotal.setText(total);
 jlblprice.setText(total);
 jlbltype.setText("Adult");
 jlblclass.setText("AC");
}

else if ((jRadioButton1.isSelected())&&  (jrsingle.isSelected()) && (jRadioButton5.isSelected()&&(jComboBox3.getSelectedItem().equals("Mymensingh"))
        ))
{
 totalCost=(VAT * MilesK8+ac -18)/100;
String vat=String.format("৳%.2f", totalCost -18);
 jlblVAT.setText(vat);
 
 String sub=String.format("৳%.2f", MilesK8+ac -18);
 jlblSub.setText(sub);
 
 String total=String.format("৳%.2f", MilesK8+totalCost+ac -18);
 jlblTotal.setText(total);
 jlblprice.setText(total);
 jlbltype.setText("Child");
 jlblclass.setText("AC");
}
else if ((jRadioButton1.isSelected())&&  (jRadioButton7.isSelected()) && (jRadioButton5.isSelected()&&(jComboBox3.getSelectedItem().equals("Mymensingh"))
        ))
{
 totalCost=(VAT * MilesK8+ac -18)/100;
String vat=String.format("৳%.2f", totalCost -18);
 jlblVAT.setText(vat);
 
 String sub=String.format("৳%.2f", MilesK8+ac *2);
 jlblSub.setText(sub);
 
 String total=String.format("৳%.2f", (MilesK8+ac+totalCost*2) -18);
 jlblTotal.setText(total);
 jlblprice.setText(total);
 jlbltype.setText("Child");
 jlblclass.setText("AC");
}


else if ((jRadioButton1.isSelected())&&  (jrsingle.isSelected()) && (jradult.isSelected()&&(jComboBox3.getSelectedItem().equals("Chittagong"))
        ))
{
 totalCost=(VAT * MilesK12+ac)/100;
String vat=String.format("৳%.2f", totalCost);
 jlblVAT.setText(vat);
 
 String sub=String.format("৳%.2f", MilesK12+ac);
 jlblSub.setText(sub);
 
 String total=String.format("৳%.2f", MilesK12+ac+totalCost);
 jlblTotal.setText(total);
 jlblprice.setText(total);
 jlbltype.setText("Adult");
 jlblclass.setText("AC");
}

else if ((jRadioButton1.isSelected())&&  (jRadioButton7.isSelected()) && (jradult.isSelected()&&(jComboBox3.getSelectedItem().equals("Chittagong"))
        ))
{
 totalCost=(VAT * MilesK8+ac*2)/100;
String vat=String.format("৳%.2f", totalCost*2);
 jlblVAT.setText(vat);
 
 String sub=String.format("৳%.2f", MilesK12+ac*2);
 jlblSub.setText(sub);
 
 String total=String.format("৳%.2f", MilesK12+ac+totalCost*2);
 jlblTotal.setText(total);
 jlblprice.setText(total);
 jlbltype.setText("Adult");
 jlblclass.setText("AC");
}

else if ((jRadioButton1.isSelected())&&  (jrsingle.isSelected()) && (jRadioButton5.isSelected()&&(jComboBox3.getSelectedItem().equals("Chittagong"))
        ))
{
 totalCost=(VAT * MilesK12+ac-18)/100;
String vat=String.format("৳%.2f", totalCost -18);
 jlblVAT.setText(vat);
 
 String sub=String.format("৳%.2f", MilesK12+ac -18);
 jlblSub.setText(sub);
 
 String total=String.format("৳%.2f", MilesK12+ac+totalCost -18);
 jlblTotal.setText(total);
 jlblprice.setText(total);
 jlbltype.setText("Child");
 jlblclass.setText("AC");
}
else if ((jRadioButton1.isSelected())&&  (jRadioButton7.isSelected()) && (jRadioButton5.isSelected()&&(jComboBox3.getSelectedItem().equals("Chittagong"))
        ))
{
 totalCost=(VAT * MilesK12+ac -18)/100;
String vat=String.format("৳%.2f", totalCost-18);
 jlblVAT.setText(vat);
 
 String sub=String.format("৳%.2f", MilesK12+ac);
 jlblSub.setText(sub);
 
 String total=String.format("৳%.2f", (MilesK12+ac+totalCost*2) -18);
 jlblTotal.setText(total);
 jlblprice.setText(total);
 jlbltype.setText("Child");
 jlblclass.setText("AC");
}


else if ((jRadioButton1.isSelected())&&  (jrsingle.isSelected()) && (jradult.isSelected()&&(jComboBox3.getSelectedItem().equals("Jessore"))
        ))
{
 totalCost=(VAT * MilesK20+ac)/100;
String vat=String.format("৳%.2f", totalCost);
 jlblVAT.setText(vat);
 
 String sub=String.format("৳%.2f", MilesK20+ac);
 jlblSub.setText(sub);
 
 String total=String.format("৳%.2f", MilesK20+ac+totalCost);
 jlblTotal.setText(total);
 jlblprice.setText(total);
 jlbltype.setText("Adult");
 jlblclass.setText("AC");
}

else if ((jRadioButton1.isSelected())&&  (jRadioButton7.isSelected()) && (jradult.isSelected()&&(jComboBox3.getSelectedItem().equals("Jessore"))
        ))
{
 totalCost=(VAT * MilesK20+ac *2)/100;
String vat=String.format("৳%.2f", totalCost*2);
 jlblVAT.setText(vat);
 
 String sub=String.format("৳%.2f", MilesK20+ac*2);
 jlblSub.setText(sub);
 
 String total=String.format("৳%.2f", MilesK20+ac+totalCost*2);
 jlblTotal.setText(total);
 jlblprice.setText(total);
 jlbltype.setText("Adult");
 jlblclass.setText("AC");
}

else if ((jRadioButton1.isSelected())&&  (jrsingle.isSelected()) && (jRadioButton5.isSelected()&&(jComboBox3.getSelectedItem().equals("Jessore"))
        ))
{
 totalCost=(VAT * MilesK20+ac -18)/100;
String vat=String.format("৳%.2f", totalCost -18);
 jlblVAT.setText(vat);
 
 String sub=String.format("৳%.2f", MilesK20+ac -18);
 jlblSub.setText(sub);
 
 String total=String.format("৳%.2f", MilesK20+ac+totalCost -18);
 jlblTotal.setText(total);
 jlblprice.setText(total);
 jlbltype.setText("Child");
 jlblclass.setText("AC");
}
else if ((jRadioButton1.isSelected())&&  (jRadioButton7.isSelected()) && (jRadioButton5.isSelected()&&(jComboBox3.getSelectedItem().equals("Jessore"))
        ))
{
 totalCost=(VAT * MilesK20+ac -18)/100;
String vat=String.format("৳%.2f", totalCost -18);
 jlblVAT.setText(vat);
 
 String sub=String.format("৳%.2f", MilesK20+ac*2);
 jlblSub.setText(sub);
 
 String total=String.format("৳%.2f", (MilesK20+ac+totalCost*2) -18);
 jlblTotal.setText(total);
 jlblprice.setText(total);
 jlbltype.setText("Child");
 jlblclass.setText("AC");
}



else if ((jRadioButton1.isSelected())&&  (jrsingle.isSelected()) && (jradult.isSelected()&&(jComboBox3.getSelectedItem().equals("Sylhet"))
        ))
{
 totalCost=(VAT * MilesK25+ac)/100;
String vat=String.format("৳%.2f", totalCost);
 jlblVAT.setText(vat);
 
 String sub=String.format("৳%.2f", MilesK25+ac);
 jlblSub.setText(sub);
 
 String total=String.format("৳%.2f", MilesK25+totalCost+ac);
 jlblTotal.setText(total);
 jlblprice.setText(total);
 jlbltype.setText("Adult");
 jlblclass.setText("AC");
}

else if ((jRadioButton1.isSelected())&&  (jRadioButton7.isSelected()) && (jradult.isSelected()&&(jComboBox3.getSelectedItem().equals("Sylhet"))
        ))
{
 totalCost=(VAT * MilesK25+ac *2)/100;
String vat=String.format("৳%.2f", totalCost*2);
 jlblVAT.setText(vat);
 
 String sub=String.format("৳%.2f", MilesK25+ac*2);
 jlblSub.setText(sub);
 
 String total=String.format("৳%.2f", MilesK25+ac+totalCost*2);
 jlblTotal.setText(total);
 jlblprice.setText(total);
 jlbltype.setText("Adult");
 jlblclass.setText("AC");
}

else if ((jRadioButton1.isSelected())&&  (jrsingle.isSelected()) && (jRadioButton5.isSelected()&&(jComboBox3.getSelectedItem().equals("Sylhet"))
        ))
{
 totalCost=(VAT * MilesK25+ac -18)/100;
String vat=String.format("৳%.2f", totalCost -18);
 jlblVAT.setText(vat);
 
 String sub=String.format("৳%.2f", MilesK25+ac -18);
 jlblSub.setText(sub);
 
 String total=String.format("৳%.2f", MilesK25+ac+totalCost -18);
 jlblTotal.setText(total);
 jlblprice.setText(total);
 jlbltype.setText("Child");
 jlblclass.setText("AC");
}
else if ((jRadioButton1.isSelected())&&  (jRadioButton7.isSelected()) && (jRadioButton5.isSelected()&&(jComboBox3.getSelectedItem().equals("Sylhet"))
        ))
{
 totalCost=(VAT * MilesK25 -18)/100;
String vat=String.format("৳%.2f", totalCost -18);
 jlblVAT.setText(vat);
 
 String sub=String.format("৳%.2f", MilesK25+ac*2);
 jlblSub.setText(sub);
 
 String total=String.format("৳%.2f", (MilesK25+ac+totalCost*2) -18);
 jlblTotal.setText(total);
 jlblprice.setText(total);
 jlbltype.setText("Child");
 jlblclass.setText("AC");
}



else if ((jRadioButton1.isSelected())&&  (jrsingle.isSelected()) && (jradult.isSelected()&&(jComboBox3.getSelectedItem().equals("Barisal"))
        ))
{
 totalCost=(VAT * MilesK25+ac)/100;
String vat=String.format("৳%.2f", totalCost);
 jlblVAT.setText(vat);
 
 String sub=String.format("৳%.2f", Miles30+ac);
 jlblSub.setText(sub);
 
 String total=String.format("৳%.2f", Miles30+totalCost+ac);
 jlblTotal.setText(total);
 jlblprice.setText(total);
 jlbltype.setText("Adult");
 jlblclass.setText("AC");
}

else if ((jRadioButton1.isSelected())&&  (jRadioButton7.isSelected()) && (jradult.isSelected()&&(jComboBox3.getSelectedItem().equals("Barisal"))
        ))
{
 totalCost=(VAT * Miles30+ac*2)/100;
String vat=String.format("৳%.2f", totalCost*2);
 jlblVAT.setText(vat);
 
 String sub=String.format("৳%.2f", Miles30+ac*2);
 jlblSub.setText(sub);
 
 String total=String.format("৳%.2f", Miles30+ac+totalCost*2);
 jlblTotal.setText(total);
 jlblprice.setText(total);
 jlbltype.setText("Adult");
 jlblclass.setText("AC");
}

else if ((jRadioButton1.isSelected())&&  (jrsingle.isSelected()) && (jRadioButton5.isSelected()&&(jComboBox3.getSelectedItem().equals("Barisal"))
        ))
{
 totalCost=(VAT * Miles30+ac -18)/100;
String vat=String.format("৳%.2f", totalCost -18);
 jlblVAT.setText(vat);
 
 String sub=String.format("৳%.2f", Miles30+ac -18);
 jlblSub.setText(sub);
 
 String total=String.format("৳%.2f", Miles30+totalCost+ac -18);
 jlblTotal.setText(total);
 jlblprice.setText(total);
 jlbltype.setText("Child");
 jlblclass.setText("AC");
}
else if ((jRadioButton1.isSelected())&&  (jRadioButton7.isSelected()) && (jRadioButton5.isSelected()&&(jComboBox3.getSelectedItem().equals("Barisal"))
        ))
{
 totalCost=(VAT * Miles30 -18)/100;
String vat=String.format("৳%.2f", totalCost -18);
 jlblVAT.setText(vat);
 
 String sub=String.format("৳%.2f", Miles30+ac*2);
 jlblSub.setText(sub);
 
 String total=String.format("৳%.2f", (Miles30+totalCost+ac*2) -18);
 jlblTotal.setText(total);
 jlblprice.setText(total);
 jlbltype.setText("Child");
 jlblclass.setText("AC");
}


    }//GEN-LAST:event_jButton1MouseClicked

    private void jlblfromActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jlblfromActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jlblfromActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
      

       
       
     
          Calendar timer=Calendar.getInstance();
       timer.getTime();
       SimpleDateFormat tTime=new SimpleDateFormat("HH:mm:ss");
    String idate=(tTime.format(timer.getTime()));
       
        SimpleDateFormat tdate=new SimpleDateFormat("dd-MMM-YYYY");
       String itime=(tdate.format(timer.getTime()));
        
 
    
        int num1;
        String ref="";
        num1=100 +(int) (Math.random()*3000);
        ref +=num1+ 100;
     
      String Firstname=(jTextField1.getText())  ;
     String Lastname=(jTextField2.getText())  ;
    String Address=(jTextField3.getText())  ;
       String Phone=(jTextField4.getText())  ;
          String Postcode=(jTextField5.getText())  ;
           String Subtotal=(jlblSub.getText());
           String Vat=(jlblVAT.getText());
           String Total=(jlblTotal.getText());
           String Ticketno=(jlblno.getText());
           String Source=        "DHAKA";
           String Destination=( jlblto.getText());
           jTextArea1.append("\t\tTicketing System:\n\n"
                   +"Ref:\t"+ref
                   +"\n================="
                   +"\nName:\t\t\t"+  Firstname
                    +"\nSure:\t\t\t"+ Lastname
                    +"\nAddress:\t\t\t"+Address
                     +"\nPhone:\t\t\t"+Phone
                   
                     +"\nPost Code:\t\t"+Postcode
                   +"\nSource:\t\t"+Source
                   +"\nDestination:\t\t"+Destination
                    +"\nTicket No:\t\t"+Ticketno
                     +"\nVat:\t\t\t"+Vat
                     +"\nSub Total:\t\t"+Subtotal
                     +"\nTotal:\t\t\t"+Total
                   +"\n Your Ticket Is Confirmed"
                   +"\n....................."
                     +"\nDate:"+  idate  +"\tTime"+itime
                 
                  
                   +"\n\n\n\t\tThanks for Using:\t\t\t"
           
           
           
           );
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void jlbltoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jlbltoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jlbltoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ticketing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ticketing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ticketing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ticketing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ticketing().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jlblSub;
    private javax.swing.JTextField jlblTotal;
    private javax.swing.JTextField jlblVAT;
    private javax.swing.JTextField jlblclass;
    private javax.swing.JTextField jlbldate;
    private javax.swing.JTextField jlblfrom;
    private javax.swing.JTextField jlblno;
    private javax.swing.JTextField jlblprice;
    private javax.swing.JTextField jlbltime;
    private javax.swing.JTextField jlblto;
    private javax.swing.JTextField jlbltype;
    private javax.swing.JRadioButton jradult;
    private javax.swing.JRadioButton jrsingle;
    private javax.swing.JRadioButton shuvon;
    // End of variables declaration//GEN-END:variables
}
